version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - myNetwork
    depends_on:
      - db

  db:
    image: mysql:8.0.20
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_PASSWORD: user
      MYSQL_USER: user
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - myNetwork

volumes:
  db-data:
networks:
  myNetwork: